enable_analytics: true
remote_theme: jekyll/minima@32468f51758b0b37c2b1f423265d4f29db461b27
caveat_banner: >
  Dear Recruiter,
  This blog is unedited and not indicative
  of how I write professionally. I thank you
  for your understanding.
minima:
  skin: dark
  social_links:
    - { platform: github,  user_url: "https://github.com/kevinnls" }
    - { platform: twitter, user_url: "https://twitter.com/kevinnlsamuel" }

author:
  name: Kevin Samuel
  email: developer@kevinnlsamuel.com
  twitter: kevinnlsamuel

title: "bite syzed tech diary"
description: >-
  (hopefully) daily journal of tech discoveries, training and the sort
baseurl: "/bitesyzedtechdiary"

incremental: true
host: 0.0.0.0

defaults:
  - scope:
      path: "index.md"
    values:
      layout: "home"
  - scope:
      type: "posts"
    values:
      layout: "post_extended"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jemoji

exclude:
  - docker-compose*.yml
  - Dockerfile*
    # - post
