theme: minima
timezone: Europe/Paris

twitter_username: kevinnlsamuel
github_username: kevinnls
title: 'bitesyzedtechtips'
description: >-
  (hopefully) daily journal of tech discoveries, training and the sort

host: 0.0.0.0

defaults:
  -
    scope:
      path: "index.md"
    values:
      layout: "home"
  -
    scope:
      type: "posts"
    values:
      layout: "post"

