remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    twitter: kevinnlsamuel
    github: kevinnls
timezone: Europe/Paris

author:
  name: kevinnls
  email: developer@kevinnlsamuel.com

title: "bitesyzedtechdiary"
description: >-
  (hopefully) daily journal of tech discoveries, training and the sort

host: 0.0.0.0

defaults:
  - scope:
      path: "index.md"
    values:
      layout: "home"
  - scope:
      type: "posts"
    values:
      layout: "post"

exclude:
  - _posts/.git
