#!/bin/sh

set -e

[ -n "${DEBUG}" ] && set -x

_date=$(date '+%F' --date="${1:-now}")

_postpattern="_posts/${_date}-*.md"

if [ -z "${post}" ]; then
    post=$(find _posts/ -name "${_postpattern##*/}")
fi

if [ -z "${post}" ]; then
    echo creating post for ${_date}
    read -p "NAME/SLUG REQUIRED: " slug
    post="${_postpattern%%\**}${slug}${_postpattern##*\*}"
fi

"${EDITOR:-vi}" "${post}"
