#!/bin/sh

set -e

[ -n "${DEBUG}" ] && set -x

convert_date_string(){ if { date '+%F' --date="${1}" 2>/dev/null;};then return 0;else >&2 echo 'invalid date string provided'; return 1;fi; }

while [ ${#} -gt 0 ]; do
	case "${1}" in
		--edit|-e)
			action=edit
			;;
		--name|-n)
			action=name
			;;
		--publish|-p)
			action=publish
			;;
		--unpublish|-u)
			action=unpublish
			;;
		--date|-d)
			_date=$(convert_date_string "${2}")
			shift 1
			;;
		--date=*)
			_date=$(convert_date_string "${1##*=}")
			;;
		*)
			_date=$(convert_date_string "${1}")
		;;
	esac
	shift 1
done

_date="${_date:-$(convert_date_string now)}"
_postpattern="${_date}-*.md"

if [ -z "${post}" ]; then
    post=$(find _drafts/ -name "${_postpattern##*/}")
fi

if [ -z "${post}" ]; then
	post=$(find _posts/ -name "${_postpattern##*/}");
fi

if [ -z "${post}" ]; then
    >&2 echo creating post for ${_date}
    >&2 read -p "NAME/SLUG REQUIRED: " slug
    post="${_postpattern%%\**}${slug// /-}${_postpattern##*\*}"
    cp -u _drafts/_post-template.md "${post}"
fi

case ${action:-name} in
	name)
		printf '%s\n' "${post}"
		;;
	edit)
		"${EDITOR:-vi}" "${post}"
		;;
	publish)
		mv "_drafts/${post##*/}" "_posts/${post##*/}"
		;;
	unpublish)
		mv "_posts/${post##*/}" "_drafts/${post##*/}"
		;;
	*)
		>&2 echo <<- EOM
		CONGRATS!

		you managed to trigger an exception
		that shouldn't have been possible

		i hate you.
		EOM
		;;
esac
